# Generated by Django 3.2.6 on 2022-01-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("user_name", models.CharField(max_length=40)),
                ("content", models.TextField()),
                ("score", models.IntegerField()),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
    ]
